name: Mirror to SAFC Repo

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to mirror repo
        run: |
          git remote add mirror https://YOUR_USERNAME:${{ secrets.MIRROR_TOKEN }}@https://github.com/omannnn9/S-AFC.git
          git push mirror main --force
